# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c640a98f3f577d64d7cc31696e235db88a45d6e7f21eb8a03f7699ad60f7c6f60d091eb443a7fee44d4bd865f9549049cfcc532d80296c6776fe3d574a22e75

test:
  secret_key_base: ee5fd30025561ab1cd159e5a59315c37ab26456dd6f92f676bc47d85bb85e880e37d7e48e3b50515486dfac16bde6d43b791fb0b3be6bdbacd2f5329c2a67f72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
